[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Changes"
versionNumber = "0.6.25"
description = "Custom mod making targeted ad-hoc adjustments/tweaks to some other mods, intended to be used only by the Lotus Écarlate modpack."
websiteUrl = "https://github.com/nbusseneau/LotusEcarlateChanges"
containsNsfwContent = false

[package.dependencies]
ASharpPen-Fall_Damage_For_Creatures = "1.1.0"
Azumatt-BowsBeforeHoes = "1.3.9"
Balrond-balrond_humanoidRandomizer = "1.3.4"
Balrond-balrond_shipyard = "1.3.9"
blacks7ar-ClayBuildPieces = "1.1.8"
blacks7ar-CoreWoodPieces = "1.1.9"
blacks7ar-FineWoodBuildPieces = "1.1.3"
blacks7ar-RefinedStonePieces = "1.0.4"
blacks7ar-RenegadeVikings = "1.2.4"
denikson-BepInExPack_Valheim = "5.4.2202"
DrakeMods-More_Gates_PlusPlus = "1.0.0"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.4"
MonsterLabZ-MonsterLabZ = "3.0.9"
Neobotics-MaxAxe = "0.4.9"
Nextek-SpeedyPaths = "1.0.8"
plumga-Clutter = "0.1.7"
Smoothbrain-Backpacks = "1.3.4"
southsil-SouthsilArmor = "3.1.3"
ValheimModding-Jotunn = "2.20.1"
Therzie-Monstrum = "1.4.2"
Therzie-Warfare = "1.7.5"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./src/bin/Release/LotusEcarlateChanges.dll"
target = "./plugins/LotusEcarlateChanges.dll"

[[build.copy]]
source = "./src/Translations"
target = "./plugins/Translations"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
