[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Changes"
versionNumber = "0.0.1"
description = "Custom mod making targeted ad-hoc adjustments/tweaks to some other mods, intended to be used only by the Lotus Écarlate modpack."
websiteUrl = "https://github.com/nbusseneau/LotusEcarlateChanges"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2202"
Therzie-Monstrum = "1.3.5"
Therzie-Warfare = "1.6.6"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./src/bin/Release/LotusEcarlateChanges.dll"
target = "./LotusEcarlateChanges.dll"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
