[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Changes"
versionNumber = "0.7.7"
description = "Custom mod making targeted ad-hoc adjustments/tweaks to some other mods, intended to be used only by the Lotus Écarlate modpack."
websiteUrl = "https://github.com/nbusseneau/LotusEcarlateChanges"
containsNsfwContent = false

[package.dependencies]
ASharpPen-Fall_Damage_For_Creatures = "1.1.0"
Balrond-balrond_containers = "1.2.9"
Balrond-balrond_humanoidRandomizer = "1.3.8"
Balrond-balrond_shipyard = "1.5.2"
blacks7ar-ClayBuildPieces = "1.2.5"
blacks7ar-CoreWoodPieces = "1.2.3"
blacks7ar-DarkWoodFurnitures = "1.0.1"
blacks7ar-FineWoodBuildPieces = "1.1.7"
blacks7ar-FineWoodFurnitures = "1.1.0"
blacks7ar-RefinedStonePieces = "1.0.9"
blacks7ar-SimpleElevators = "1.2.9"
denikson-BepInExPack_Valheim = "5.4.2332"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.4"
Neobotics-MaxAxe = "0.5.7"
Nextek-SpeedyPaths = "1.0.8"
plumga-Clutter = "0.1.7"
shudnal-MoreGatesExtended = "1.0.2"
southsil-SouthsilArmor = "3.1.7"
Therzie-Monstrum = "1.5.1"
Therzie-Warfare = "1.8.9"
ValheimModding-Jotunn = "2.26.1"
VentureValheim-World_Advancement_Progression = "0.3.6"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./src/bin/Release/LotusEcarlateChanges.dll"
target = "./plugins/LotusEcarlateChanges.dll"

[[build.copy]]
source = "./src/Translations"
target = "./plugins/Translations"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
