[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Changes"
versionNumber = "0.5.0"
description = "Custom mod making targeted ad-hoc adjustments/tweaks to some other mods, intended to be used only by the Lotus Écarlate modpack."
websiteUrl = "https://github.com/nbusseneau/LotusEcarlateChanges"
containsNsfwContent = false

[package.dependencies]
Balrond-balrond_shipyard = "1.3.7"
blacks7ar-ClayBuildPieces = "1.1.0"
blacks7ar-CoreWoodPieces = "1.1.6"
blacks7ar-FineWoodBuildPieces = "1.0.8"
ComfyMods-PotteryBarn = "1.13.0"
denikson-BepInExPack_Valheim = "5.4.2202"
DrakeMods-More_Gates_PlusPlus = "1.0.0"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.3"
plumga-Clutter = "0.1.6"
Soloredis-RtDBiomes = "2.1.3"
southsil-SouthsilArmor = "3.0.5"
Therzie-Monstrum = "1.3.8"
Therzie-Warfare = "1.6.8"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./src/bin/Release/LotusEcarlateChanges.dll"
target = "./LotusEcarlateChanges.dll"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
