[config]
schemaVersion = "0.0.1"


[package]
namespace = "Lotus_Ecarlate"
name = "Lotus_Ecarlate_Changes"
versionNumber = "0.5.1"
description = "Custom mod making targeted ad-hoc adjustments/tweaks to some other mods, intended to be used only by the Lotus Écarlate modpack."
websiteUrl = "https://github.com/nbusseneau/LotusEcarlateChanges"
containsNsfwContent = false

[package.dependencies]
ASharpPen-Fall_Damage_For_Creatures = "1.1.0"
Azumatt-BowsBeforeHoes = "1.3.6"
Balrond-balrond_shipyard = "1.3.8"
blacks7ar-ClayBuildPieces = "1.1.7"
blacks7ar-CoreWoodPieces = "1.1.8"
blacks7ar-FineWoodBuildPieces = "1.1.1"
blacks7ar-RefinedStonePieces = "1.0.2"
denikson-BepInExPack_Valheim = "5.4.2202"
DrakeMods-More_Gates_PlusPlus = "1.0.0"
Goldenrevolver-Cape_And_Torch_Resistance_Rework_And_New_Water_And_Cold_Resistance = "1.0.3"
MonsterLabZ-MonsterLabZ = "3.0.9"
plumga-Clutter = "0.1.7"
Smoothbrain-Backpacks = "1.3.3"
southsil-SouthsilArmor = "3.0.5"
Therzie-Monstrum = "1.4.0"
Therzie-Warfare = "1.7.4"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./src/bin/Release/LotusEcarlateChanges.dll"
target = "./plugins/LotusEcarlateChanges.dll"

[[build.copy]]
source = "./src/Translations"
target = "./plugins/Translations"


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim", ]
